using System;
using Microsoft.CodeAnalysis;

namespace Keepi.Generators;

[AttributeUsage(AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
public sealed class GenerateTestContextAttribute : Attribute
{
    public const string FullName = "Keepi.Generators.GenerateTestContextAttribute";

    /// <summary>
    /// The type the test context is made for. This parameter is required for
    /// the majority of code that could be generated by the generator.
    /// </summary>
    public Type TargetType { get; set; }

    /// <summary>
    /// Whether the WithXCall methods should be generated automatically. It will
    /// generated a simple moq setup for each public or internal method of the
    /// target type with return value if applicable. The arguments of the method
    /// are not verified in the generated Setup code, verification is expected
    /// to be done manually, with usually a VerifyNoOtherLogging call at the end
    /// to assert all calls were expected and set up.
    ///
    /// For the Microsoft ILogger interface methods are never generated.
    ///
    /// By default no WithXCall methods are generated.
    /// </summary>
    public bool GenerateWithCallMethods { get; set; }

    /// <summary>
    /// Indicate whether the generated VerifyNoOtherCalls method should verify
    /// the mocked logger. By default logger mocks are not verified.
    /// </summary>
    public bool VerifyLogging { get; set; }
}

// This class is defined here on purpose since it must be kept in sync with the attribute definition above.
internal sealed class GenerateTestContextAttributeData
{
    public GenerateTestContextAttributeData(
        INamedTypeSymbol targetType,
        bool generateWithCallMethods,
        bool verifyLogging
    )
    {
        TargetType = targetType ?? throw new ArgumentNullException(paramName: nameof(targetType));
        GenerateWithCallMethods = generateWithCallMethods;
        VerifyLogging = verifyLogging;
    }

    public INamedTypeSymbol TargetType { get; }
    public bool GenerateWithCallMethods { get; }
    public bool VerifyLogging { get; }
}
