// <auto-generated />
using System;
using Keepi.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Keepi.Infrastructure.Data.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260125163239_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("Keepi.Infrastructure.Data.Entries.UserEntryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("InvoiceItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Minutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Remark")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("InvoiceItemId");

                    b.HasIndex("UserId");

                    b.ToTable("UserEntries");
                });

            modelBuilder.Entity("Keepi.Infrastructure.Data.InvoiceItems.InvoiceItemEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("Name", "ProjectId")
                        .IsUnique();

                    b.ToTable("InvoiceItems");
                });

            modelBuilder.Entity("Keepi.Infrastructure.Data.Projects.ProjectEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Keepi.Infrastructure.Data.Projects.ProjectEntityUserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("ProjectId", "UserId")
                        .IsUnique();

                    b.ToTable("ProjectUsers");
                });

            modelBuilder.Entity("Keepi.Infrastructure.Data.UserInvoiceItemCustomizations.UserInvoiceItemCustomizationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("Color")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InvoiceItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceItemId");

                    b.HasIndex("UserId", "InvoiceItemId")
                        .IsUnique();

                    b.ToTable("UserInvoiceItemCustomizations");
                });

            modelBuilder.Entity("Keepi.Infrastructure.Data.Users.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("EntriesPermission")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExportsPermission")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("IdentityOrigin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectsPermission")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsersPermission")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EmailAddress")
                        .IsUnique();

                    b.HasIndex("IdentityOrigin", "ExternalId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Keepi.Infrastructure.Data.Entries.UserEntryEntity", b =>
                {
                    b.HasOne("Keepi.Infrastructure.Data.InvoiceItems.InvoiceItemEntity", "InvoiceItem")
                        .WithMany("UserEntries")
                        .HasForeignKey("InvoiceItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Keepi.Infrastructure.Data.Users.UserEntity", "User")
                        .WithMany("Entries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InvoiceItem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Keepi.Infrastructure.Data.InvoiceItems.InvoiceItemEntity", b =>
                {
                    b.HasOne("Keepi.Infrastructure.Data.Projects.ProjectEntity", "Project")
                        .WithMany("InvoiceItems")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Keepi.Infrastructure.Data.Projects.ProjectEntityUserEntity", b =>
                {
                    b.HasOne("Keepi.Infrastructure.Data.Projects.ProjectEntity", "Project")
                        .WithMany("ProjectUsers")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Keepi.Infrastructure.Data.Users.UserEntity", "User")
                        .WithMany("ProjectUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Keepi.Infrastructure.Data.UserInvoiceItemCustomizations.UserInvoiceItemCustomizationEntity", b =>
                {
                    b.HasOne("Keepi.Infrastructure.Data.InvoiceItems.InvoiceItemEntity", "InvoiceItem")
                        .WithMany("UserInvoiceItemCustomizations")
                        .HasForeignKey("InvoiceItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Keepi.Infrastructure.Data.Users.UserEntity", "User")
                        .WithMany("UserInvoiceItemCustomizations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InvoiceItem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Keepi.Infrastructure.Data.InvoiceItems.InvoiceItemEntity", b =>
                {
                    b.Navigation("UserEntries");

                    b.Navigation("UserInvoiceItemCustomizations");
                });

            modelBuilder.Entity("Keepi.Infrastructure.Data.Projects.ProjectEntity", b =>
                {
                    b.Navigation("InvoiceItems");

                    b.Navigation("ProjectUsers");
                });

            modelBuilder.Entity("Keepi.Infrastructure.Data.Users.UserEntity", b =>
                {
                    b.Navigation("Entries");

                    b.Navigation("ProjectUsers");

                    b.Navigation("UserInvoiceItemCustomizations");
                });
#pragma warning restore 612, 618
        }
    }
}
